version: "3.7"

services:
  php:
    container_name: brewmap-php
    working_dir: /application
    image: php:7.4.6-fpm-alpine
    volumes:
      - .:/application
    restart: always

  web:
    container_name: brewmap-web
    image: nginx:alpine
    working_dir: /application
    volumes:
      - .:/application
      - ./environment/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "13000:80"
    depends_on:
      - php
    restart: always

  composer:
    container_name: brewmap-composer
    image: composer:1.10.6
    volumes:
      - .:/application

